# Generated by Django 5.1.3 on 2024-11-13 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.TextField()),
                ('edad', models.IntegerField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materias', to='CALIFICACIONES.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CALIFICACIONES.estudiantes')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='CALIFICACIONES.materia')),
            ],
        ),
    ]
